News about OSS contributions
hms-dbmi/gehlenborglab-website pull request #229
Opened 2020-10-30 23:19 UTC by mccalluc

Are the descriptions of your work accurate? Is my example too trivial? Anyone else in the lab we should nudge to add a line?

2020-10-30 23:33 UTC, ilan-gold approved these changes

2020-10-30 23:33 UTC, ilan-gold commented on _news/2020-11-01-os-contributions.md
> +  [dozens](https://github.com/cypress-io/cypress-documentation/pull/195/files) of it's/its mistakes in the cypress.io docs.
Not too trivial at all :)

2020-10-30 23:33 UTC, ilan-gold commented on _news/2020-11-01-os-contributions.md
> +  [dozens](https://github.com/cypress-io/cypress-documentation/pull/195/files) of it's/its mistakes in the cypress.io docs.
Also deck.gl! https://github.com/visgl/deck.gl/pulls?q=is%3Apr+author%3Amccalluc

2020-11-02 02:16 UTC, manzt approved these changes
Great, thanks for writing this up @mccalluc!

2020-11-02 14:36 UTC, mccalluc commented
@ngehlenborg : Tone ok? It felt like there was something worth advertising here that cut across projects. Do you know if there's anyone else in the lab we should nudge?

2020-11-06 10:26 UTC, ngehlenborg requested changes

2020-11-06 10:26 UTC, ngehlenborg commented on _news/2020-11-01-os-contributions.md
> +- Open source isn't just about code. Chuck can be nit-picky about grammar,
Can we change that to "Open source isn't just about code. Chuck McCallum has contributed to the documentation of [Cypress.io](https://github.com/cypress-io/cypress-documentation/pull/195/files) and [Deck.gl](https://github.com/visgl/deck.gl/pulls?q=is%3Apr+author%3Amccalluc)".

2020-11-06 14:55 UTC, mccalluc commented on _news/2020-11-01-os-contributions.md
> +  [typos](https://github.com/visgl/deck.gl/pulls?q=is%3Apr+author%3Amccalluc) in the deck.gl docs.
```suggestion
- Open source isn't just about code. Chuck McCallum has contributed to the documentation of
  [Cypress.io](https://github.com/cypress-io/cypress-documentation/pull/195/files)
  and [Deck.gl](https://github.com/visgl/deck.gl/pulls?q=is%3Apr+author%3Amccalluc).
```

2020-11-06 14:56 UTC, merged