Add Furui Cheng's profile
hms-dbmi/gehlenborglab-website pull request #321
Opened 2022-04-04 08:22 UTC by ChengFR

2022-04-05 22:11 UTC, ngehlenborg requested changes
Great! Please address the suggested edits and after that it will be ready to merge.

2022-04-05 22:11 UTC, ngehlenborg commented on _members/furui-cheng.md
> +His research interest lies in the field of **Human-Center AI** with data visualization. He designs and develops **Interactive Visualization Systems** to support users with no Machine Learning backgro
```suggestion
His research interest lies in the field of **Human-Centered AI** with data visualization. He designs and develops **Interactive Visualization Systems** to support users with no Machine Learning background in understanding and exploring ML models.
```

2022-04-05 22:11 UTC, ngehlenborg commented on _members/furui-cheng.md
> +job_title: Visiting Graduate Student in Computer Science
```suggestion
job_title: Visiting Graduate Student
```

2022-04-06 02:58 UTC, ChengFR commented
Thanks, Nils! I've addressed the issues.

2022-04-06 11:56 UTC, merged