Adding a hybrid appraoch paper to publications
hms-dbmi/gehlenborglab-website pull request #432
Opened 2024-07-15 16:15 UTC by EricMoerthVis

2024-07-15 21:53 UTC, lchoy requested changes

2024-07-15 21:53 UTC, lchoy commented on _publications/moerth-2024-hybrid-approach-osf.md
> +  authors: " Mörth, Eric, Cydney Nielsen, Morgan Turner, Liu Xianhao, Mark S. Keller, Johanna Beyer, Hanspeter Pfister, Chen Zhu-Tian, Gehlenborg"
```suggestion
  authors: "Eric Mörth, Cydney Nielsen, Morgan Turner, Liu Xianhao, Mark S. Keller, Johanna Beyer, Hanspeter Pfister, Chen Zhu-Tian, Nils Gehlenborg"
```

Modified to list authors as "First Last". A mix will cause confusion.

2024-07-15 21:53 UTC, lchoy commented on _publications/moerth-2024-hybrid-approach-osf.md
> +  - nils-gehlenborg
```suggestion
members:
  - moerth-eric
  - mark-keller
  - nils-gehlenborg
```

Not entirely sure if this matters, but this makes the formatting consistent with other pages.

2024-07-16 15:48 UTC, EricMoerthVis commented on _publications/moerth-2024-hybrid-approach-osf.md
> +  authors: " Mörth, Eric, Cydney Nielsen, Morgan Turner, Liu Xianhao, Mark S. Keller, Johanna Beyer, Hanspeter Pfister, Chen Zhu-Tian, Gehlenborg"
Thank you for catching that!

2024-07-16 18:15 UTC, lchoy approved these changes

2024-07-16 18:16 UTC, merged