Update eric moerth information
hms-dbmi/gehlenborglab-website pull request #433
Opened 2024-07-15 16:23 UTC by EricMoerthVis

Updating my information on the website and adding myself to the projects I am actively working on.

2024-07-15 21:42 UTC, lchoy requested changes
A couple minor suggestions.

2024-07-15 21:42 UTC, lchoy commented on _members/eric-moerth.md
> +Eric Moerth is a Post Doctoral Specialist Research Fellow in the Department of Biomedical Informatics at Harvard Medical School (DBMI) and part of the HIDIVE Lab. He received his PhD from the Univers
```suggestion
Eric Moerth is a Post Doctoral Specialist Research Fellow in the Department of Biomedical Informatics at Harvard Medical School (DBMI) and part of the HIDIVE Lab. He received his PhD from the University of Bergen in Norway. During his PhD study, Eric Moerth conducted research in multimodal medical visualization. His focus was the research of new and innovative ways to visualize and explore medical data. Now Eric is researching the visualization of large-scale 3D Tissue Images using novel rendering techniques. Furthermore, his research enables the efficient analysis of highly multiplexed tissue images, and he also investigates how novel output devices like virtual and augmented reality devices can help investigators make better sense of their data.
```

Minor grammatical fix to add period after second sentence.

2024-07-15 21:42 UTC, lchoy commented on _members/eric-moerth.md
> +[Eric Moerth] is a Research Fellow in Biomedical Informatics at Harvard Medical School.
```suggestion
Eric Moerth is a Research Fellow in Biomedical Informatics at Harvard Medical School.
```

The square brackets are not needed if there's no link.

2024-07-16 15:48 UTC, EricMoerthVis commented
Thank you for the suggestions, I commited them

2024-07-16 18:17 UTC, lchoy approved these changes

2024-07-16 18:18 UTC, merged