A11y microsite
hms-dbmi/gehlenborglab-website pull request #537
Opened 2024-10-23 18:12 UTC by LDubya

Placeholder for a11y microsite pull request. Description of modifications and new functionality can go here.

2024-10-24 15:48 UTC, sehilyi commented on _teams/accessibility/research-in-biomedical-accessibility.md
> +name: Research in Biomedical Accessibility
To make it consistent with our paper (i.e., biomedical → life sciences).

```suggestion
name: Accessibility in Life Sciences Data Resources
```

2024-10-24 15:48 UTC, sehilyi commented on _teams/accessibility/research-in-biomedical-accessibility.md
> +## Evaluation of Accessibility in Biomedical Resources
```suggestion
## Evaluation of Accessibility in Life Sciences Data Resources
```

2024-10-24 15:52 UTC, sehilyi commented on _teams/accessibility/research-in-biomedical-accessibility.md
> +- **Tools Used**: We employed computational accessibility tools such as WAVE and Axe to conduct our analysis.
A bit of revision to highlight the scientific contribution better

```suggestion
- **Mixed-methods Approach**: We employed computational accessibility tools, such as WAVE and Axe, to conduct our analysis at scale, in addition to conducting user evaluation for selected resources.
```

2024-10-24 15:52 UTC, sehilyi commented on _teams/accessibility/research-in-biomedical-accessibility.md
> +Our primary goal is to improve the accessibility of biomedical resources by identifying the key barriers and developing strategies to address them. Through this work, we aim to ensure that biomedical
```suggestion
Our primary goal is to improve the accessibility of life sciences resources by identifying the key barriers and developing strategies to address them. Through this work, we aim to ensure that biomedical websites and tools comply with the Web Content Accessibility Guidelines (WCAG) and are accessible to people with disabilities.
```

2024-10-24 15:53 UTC, sehilyi commented on _teams/accessibility/research-in-biomedical-accessibility.md
> +Our evaluation revealed that nearly all of the assessed websites (96%) had severe accessibility issues. The most common issue identified was the absence of crucial metadata, such as alternative text
```suggestion
Our evaluation revealed that nearly all of the assessed websites (96%) had severe accessibility issues. The most common issue identified was the absence of crucial metadata, such as alternative text for images, which creates significant barriers for users with blindness and low vision (BLV). Without such metadata, it is impossible for BLV users to fully understand the content displayed in life sciences data visualizations (Refer to the figure on the top).
```

2024-10-24 15:53 UTC, sehilyi commented on _teams/accessibility/research-in-biomedical-accessibility.md
> +- **Addressing Gaps**: Our findings highlight the need for improving accessibility across biomedical websites, particularly in providing alternative texts and complying with WCAG.
```suggestion
- **Addressing Gaps**: Our findings highlight the need for improving accessibility across life sciences websites, particularly in providing alternative texts and complying with WCAG.
```

2024-10-24 15:57 UTC, sehilyi commented on _teams/accessibility/research-in-biomedical-accessibility.md
> +We invite you to participate in this effort. We are looking for feedback and suggestions from the broader scientific and accessibility communities and potential collaborations for academic and non-ac
```suggestion
---
# make sure to add page to _data/teams.yml

name: Accessibility in Life Sciences Data Resources
team_id: accessibility
active: true

image: a11y-results.png
image_alt: A figure containing three graphs. Graph A shows that 96% of data portals have issues. Graph B shows the percentage of those issues by accessibility categories, with contrast being the most prevalent issue, and label_missing, alt_missing, and label_empty highlighted. Graph C is a pie chart showing that 78.8% of alt text in journals are entirely missing, while 21.3% are uninformative.

publications:
  - lyi-2024-F8FYKQP6

---

## Evaluation of Accessibility in Life Sciences Data Resources

Our lab has been conducting extensive research evaluating the accessibility of life sciences websites and data resources. In this ongoing project, we assessed over 3,000 data portals and journal websites using accessibility evaluation tools, like [WAVE](https://wave.webaim.org) and [Axe](https://www.deque.com/axe/). We also evaluated selected data portals with an actual screen reader users to identify real-world barriers for performing important tasks (e.g., data discovery).

## Current Accessibility Status
Our evaluation revealed that nearly all assessed websites (96%) had severe accessibility issues. The most common issue identified was the absence of crucial metadata, such as alternative text for images, which creates significant barriers for users with blindness and low vision (BLV). Without such metadata, it is impossible for BLV users to fully understand the content displayed in life sciences data visualizations (Refer to the figure on the top).

## Research Aims
Our primary goal is to improve the accessibility of life sciences resources by identifying the key barriers and developing strategies to address them. Through this work, we aim to ensure that life sciences websites and tools comply with the Web Content Accessibility Guidelines (WCAG) and are accessible to people with disabilities.

## Our Contributions
- **Evaluation Results**: We identified a range of accessibility failures, with missing alt texts being one of the most prevalent issues.
- **Mixed-methods Approach**: We employed computational accessibility tools to conduct our analysis at scale, in addition to conducting user evaluation for selected resources.
- **Addressing Gaps**: Our findings highlight the need for improving accessibility across life sciences websites, particularly in providing alternative texts and complying with WCAG.

## Call to Action
We invite you to participate in this effort. We seek feedback and suggestions from the broader scientific and accessibility communities and potential collaborations for academic and non-academic activities.
```

2024-11-01 12:34 UTC, thomcsmits reviewed
Added some changes here as well: https://github.com/LDubya/gehlenborglab-website/pull/16

2024-11-01 12:34 UTC, thomcsmits commented on _teams/accessibility/our-accessibility-journey.md
> +
I don't really see the added value of adding degree titles to the text? It also makes it a bit harder to read. If someone is interested in degrees, they can always check out the individual pages. Perhaps we can even hyperlink these directly from this text?

2024-11-01 15:23 UTC, thomcsmits requested changes

2024-11-01 15:23 UTC, thomcsmits commented on _teams/accessibility/our-accessibility-journey.md
> +The preprint was accepted for presentation at the AccessViz workshop at IEEE VIS 2024.
```suggestion
The preprint was accepted for presentation at the AccessViz workshop at IEEE VIS 2024. 

We also looked into mental models of visualizations related to individuals who are blind, led by by {% include get-name-degree.html title="Thomas Smits" %}. The preprint for this was also accepted for presentation at the AccessViz workshop at IEEE VIS 2024.
```

2024-11-01 15:45 UTC, sehilyi commented on _teams/accessibility/our-accessibility-journey.md
> +
Sehi to add a paragraph about the K

2024-11-01 15:58 UTC, thomcsmits commented on _teams/accessibility/our-accessibility-journey.md
> +{% include get-member-url.html title="Andrew Mar" %}'s contributions were instrumental in the paper *Explaining Unfamiliar Genomics Data Visualizations to a Blind Individual through Transitions*, whi
```suggestion
{% include get-member-url.html title="Andrew Mar" %}'s contributions were instrumental in the paper *Explaining Unfamiliar Genomics Data Visualizations to a Blind Individual through Transitions*, which was accepted for presentation at the AccessViz workshop at IEEE VIS 2024. 

We also looked into mental models of visualizations related to individuals who are blind, led by by {% include get-name-degree.html title="Thomas Smits" %}. The preprint for this was also accepted for presentation at the AccessViz workshop at IEEE VIS 2024.
```

2024-11-01 16:03 UTC, sehilyi commented on _teams/accessibility/our-accessibility-journey.md
> +
```suggestion

Our accessibility efforts led to more opportunities to expand our work. {% include get-member-url.html title="Sehi L'Yi" %} has recently received the NIH K99/R00 Pathway to Independence Award to continue work on accessibility. This project proposes to increase the diversity of the genomics workforce through accessible data and visualization. This includes conducting comprehensive evaluations of existing biomedical data resources and building tools and frameworks that can increase the accessibility of biomedical research and education. This grant will help {% include get-member-url.html title="Sehi L'Yi" %} to build an independent research group to work on this area in the future.

```

2024-11-01 16:03 UTC, thomcsmits commented on _teams/accessibility/our-accessibility-journey.md
> +we began quantifying the state accessibility of research journals and data portals, crucial for biomedical research, in a project led by {% include get-member-url.html title="Sehi L'Yi" %}.
```suggestion
we began quantifying the state accessibility of research journals and data portals, crucial for biomedical research, in a project led by Sehi L'Yi.
```

2024-11-01 16:03 UTC, thomcsmits commented on _teams/accessibility/our-accessibility-journey.md
> +{% include get-member-url.html title="Andrew Mar" %}'s contributions were instrumental in the paper *Explaining Unfamiliar Genomics Data Visualizations to a Blind Individual through Transitions*, whi
```suggestion
Andrew Mar's contributions were instrumental in the paper *Explaining Unfamiliar Genomics Data Visualizations to a Blind Individual through Transitions*, which was accepted for presentation at the AccessViz workshop at IEEE VIS 2024.
```

2024-11-01 16:03 UTC, sehilyi commented on _teams/accessibility/our-accessibility-journey.md
> +
```suggestion

Our accessibility efforts led to more opportunities to expand our work. {% include get-member-url.html title="Sehi L'Yi" %} has recently received the NIH K99/R00 Pathway to Independence Award to continue work on accessibility. This project proposes to increase the diversity of the genomics workforce through accessible data and visualization. This includes conducting comprehensive evaluations of existing biomedical data resources and building tools and frameworks that can increase the accessibility of biomedical research and education. This grant will help {% include get-member-url.html title="Sehi L'Yi" %} to build an independent research group to work on this area in the future.

```

2024-11-01 17:46 UTC, thomcsmits commented on _teams/accessibility/our-accessibility-journey.md
> +The HIDIVE Lab accessibility research, led by {% include get-member-url.html title="Sehi L'Yi" %}, initially focused on improving screen reader accessibility for data visualizations.
```suggestion
The HIDIVE Lab accessibility research, led by {% include get-member-url.html title="Sehi L'Yi" %}, initially focused on improving accessibility for genome-mapped data visualizations. 
```

2024-11-01 17:46 UTC, thomcsmits commented on _teams/accessibility/our-accessibility-journey.md
> +Recognizing that grammar-based visualization tools like the Gosling toolkit could be converted into meaningful text descriptions, {% include get-member-url.html title="Thomas Smits" %} led the AltGos
```suggestion
Recognizing that grammar-based visualization tools like the Gosling toolkit could be converted into meaningful text descriptions, {% include get-member-url.html title="Thomas Smits" %} led the AltGosling project to automate description generation for genomics data visualizations.
```

2024-11-01 17:51 UTC, thomcsmits commented on teams.md
> +            alt="{{ team.gallery.first[1] }}"></a>
@LDubya am I correct to see here that the image and alt don't match indices?
```suggestion
<a href="{{team.url}}"><img class="thumb"
            src="/assets/img/publications/thumbnail/{{ team.gallery.first[0] }}"
            alt="{{ team.gallery.first[0] }}"></a>
```

2024-11-01 19:13 UTC, LDubya commented on teams.md
> +            alt="{{ team.gallery.first[1] }}"></a>
The indices follow the gallery format, so `0` index is the filename and `1` index is the description

```
gallery:
  cistrome-explorer.png: 'Cistrome Explorer provides scalable, interactive, and modular visualizations for epigenomics data with associated metadata.'
  cistrome-explorer-toolkit.png: 'Cistrome Explorer integrated Cistrome DB Toolkit that contains huge collection of public ChIP-seq, DNase-seq, and ATAC-seq datasets.'
```

2024-11-01 19:19 UTC, thomcsmits approved these changes
LGTM!

2024-11-01 19:20 UTC, merged